# Site Settings
title: Sudoquest Game Design
email: pyroticblaziken@gmail.com
description: >-
  Game Design Documentation for Sudoquest

# Build Settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages
  - _posts

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      shared: true
      relate: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _sudoquest
  - scope:
      path: "_sudoquest"
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: 

